// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testDataLogs(t *testing.T) {
	t.Parallel()

	query := DataLogs()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testDataLogsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DataLog{}
	if err = randomize.Struct(seed, o, dataLogDBTypes, true, dataLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DataLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := DataLogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDataLogsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DataLog{}
	if err = randomize.Struct(seed, o, dataLogDBTypes, true, dataLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DataLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := DataLogs().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := DataLogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDataLogsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DataLog{}
	if err = randomize.Struct(seed, o, dataLogDBTypes, true, dataLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DataLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := DataLogSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := DataLogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDataLogsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DataLog{}
	if err = randomize.Struct(seed, o, dataLogDBTypes, true, dataLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DataLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := DataLogExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if DataLog exists: %s", err)
	}
	if !e {
		t.Errorf("Expected DataLogExists to return true, but got false.")
	}
}

func testDataLogsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DataLog{}
	if err = randomize.Struct(seed, o, dataLogDBTypes, true, dataLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DataLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	dataLogFound, err := FindDataLog(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if dataLogFound == nil {
		t.Error("want a record, got nil")
	}
}

func testDataLogsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DataLog{}
	if err = randomize.Struct(seed, o, dataLogDBTypes, true, dataLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DataLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = DataLogs().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testDataLogsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DataLog{}
	if err = randomize.Struct(seed, o, dataLogDBTypes, true, dataLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DataLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := DataLogs().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testDataLogsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	dataLogOne := &DataLog{}
	dataLogTwo := &DataLog{}
	if err = randomize.Struct(seed, dataLogOne, dataLogDBTypes, false, dataLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DataLog struct: %s", err)
	}
	if err = randomize.Struct(seed, dataLogTwo, dataLogDBTypes, false, dataLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DataLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = dataLogOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = dataLogTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := DataLogs().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testDataLogsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	dataLogOne := &DataLog{}
	dataLogTwo := &DataLog{}
	if err = randomize.Struct(seed, dataLogOne, dataLogDBTypes, false, dataLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DataLog struct: %s", err)
	}
	if err = randomize.Struct(seed, dataLogTwo, dataLogDBTypes, false, dataLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DataLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = dataLogOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = dataLogTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DataLogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func dataLogBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *DataLog) error {
	*o = DataLog{}
	return nil
}

func dataLogAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *DataLog) error {
	*o = DataLog{}
	return nil
}

func dataLogAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *DataLog) error {
	*o = DataLog{}
	return nil
}

func dataLogBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *DataLog) error {
	*o = DataLog{}
	return nil
}

func dataLogAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *DataLog) error {
	*o = DataLog{}
	return nil
}

func dataLogBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *DataLog) error {
	*o = DataLog{}
	return nil
}

func dataLogAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *DataLog) error {
	*o = DataLog{}
	return nil
}

func dataLogBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *DataLog) error {
	*o = DataLog{}
	return nil
}

func dataLogAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *DataLog) error {
	*o = DataLog{}
	return nil
}

func testDataLogsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &DataLog{}
	o := &DataLog{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, dataLogDBTypes, false); err != nil {
		t.Errorf("Unable to randomize DataLog object: %s", err)
	}

	AddDataLogHook(boil.BeforeInsertHook, dataLogBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	dataLogBeforeInsertHooks = []DataLogHook{}

	AddDataLogHook(boil.AfterInsertHook, dataLogAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	dataLogAfterInsertHooks = []DataLogHook{}

	AddDataLogHook(boil.AfterSelectHook, dataLogAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	dataLogAfterSelectHooks = []DataLogHook{}

	AddDataLogHook(boil.BeforeUpdateHook, dataLogBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	dataLogBeforeUpdateHooks = []DataLogHook{}

	AddDataLogHook(boil.AfterUpdateHook, dataLogAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	dataLogAfterUpdateHooks = []DataLogHook{}

	AddDataLogHook(boil.BeforeDeleteHook, dataLogBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	dataLogBeforeDeleteHooks = []DataLogHook{}

	AddDataLogHook(boil.AfterDeleteHook, dataLogAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	dataLogAfterDeleteHooks = []DataLogHook{}

	AddDataLogHook(boil.BeforeUpsertHook, dataLogBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	dataLogBeforeUpsertHooks = []DataLogHook{}

	AddDataLogHook(boil.AfterUpsertHook, dataLogAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	dataLogAfterUpsertHooks = []DataLogHook{}
}

func testDataLogsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DataLog{}
	if err = randomize.Struct(seed, o, dataLogDBTypes, true, dataLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DataLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DataLogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testDataLogsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DataLog{}
	if err = randomize.Struct(seed, o, dataLogDBTypes, true); err != nil {
		t.Errorf("Unable to randomize DataLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(dataLogColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := DataLogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testDataLogToOneTrackedDeviceUsingTrackedDevice(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local DataLog
	var foreign TrackedDevice

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, dataLogDBTypes, false, dataLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DataLog struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, trackedDeviceDBTypes, false, trackedDeviceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackedDevice struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.TrackedDeviceID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.TrackedDevice().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := DataLogSlice{&local}
	if err = local.L.LoadTrackedDevice(ctx, tx, false, (*[]*DataLog)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.TrackedDevice == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.TrackedDevice = nil
	if err = local.L.LoadTrackedDevice(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.TrackedDevice == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testDataLogToOneSetOpTrackedDeviceUsingTrackedDevice(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a DataLog
	var b, c TrackedDevice

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, dataLogDBTypes, false, strmangle.SetComplement(dataLogPrimaryKeyColumns, dataLogColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, trackedDeviceDBTypes, false, strmangle.SetComplement(trackedDevicePrimaryKeyColumns, trackedDeviceColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, trackedDeviceDBTypes, false, strmangle.SetComplement(trackedDevicePrimaryKeyColumns, trackedDeviceColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*TrackedDevice{&b, &c} {
		err = a.SetTrackedDevice(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.TrackedDevice != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.DataLogs[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.TrackedDeviceID != x.ID {
			t.Error("foreign key was wrong value", a.TrackedDeviceID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.TrackedDeviceID))
		reflect.Indirect(reflect.ValueOf(&a.TrackedDeviceID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.TrackedDeviceID != x.ID {
			t.Error("foreign key was wrong value", a.TrackedDeviceID, x.ID)
		}
	}
}

func testDataLogsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DataLog{}
	if err = randomize.Struct(seed, o, dataLogDBTypes, true, dataLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DataLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testDataLogsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DataLog{}
	if err = randomize.Struct(seed, o, dataLogDBTypes, true, dataLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DataLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := DataLogSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testDataLogsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DataLog{}
	if err = randomize.Struct(seed, o, dataLogDBTypes, true, dataLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DataLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := DataLogs().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	dataLogDBTypes = map[string]string{`ID`: `bigint`, `TrackedDeviceID`: `bigint`, `LogTime`: `timestamp without time zone`, `SensorValue`: `integer`}
	_              = bytes.MinRead
)

func testDataLogsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(dataLogPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(dataLogAllColumns) == len(dataLogPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &DataLog{}
	if err = randomize.Struct(seed, o, dataLogDBTypes, true, dataLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DataLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DataLogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, dataLogDBTypes, true, dataLogPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize DataLog struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testDataLogsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(dataLogAllColumns) == len(dataLogPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &DataLog{}
	if err = randomize.Struct(seed, o, dataLogDBTypes, true, dataLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DataLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DataLogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, dataLogDBTypes, true, dataLogPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize DataLog struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(dataLogAllColumns, dataLogPrimaryKeyColumns) {
		fields = dataLogAllColumns
	} else {
		fields = strmangle.SetComplement(
			dataLogAllColumns,
			dataLogPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := DataLogSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testDataLogsUpsert(t *testing.T) {
	t.Parallel()

	if len(dataLogAllColumns) == len(dataLogPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := DataLog{}
	if err = randomize.Struct(seed, &o, dataLogDBTypes, true); err != nil {
		t.Errorf("Unable to randomize DataLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert DataLog: %s", err)
	}

	count, err := DataLogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, dataLogDBTypes, false, dataLogPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize DataLog struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert DataLog: %s", err)
	}

	count, err = DataLogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
